name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint || echo "No linting configured"

      - name: Run tests
        run: npm test || echo "No tests configured"

      - name: Verify server starts
        run: |
          node --check server.js
